FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

EXPOSE 5000

CMD exec gunicorn --bind :5000 --workers 2 --threads 4 --timeout 120 \
    --worker-class eventlet "app:create_app()"
